//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Benefits
    {
        public int BenefitID { get; set; }
        public string Details { get; set; }
        public string Image { get; set; }
        public Nullable<int> price { get; set; }
    
        public virtual SuppliersBenefits SuppliersBenefits { get; set; }
    }
}
