//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Workers()
        {
            this.WorkersBenefits = new HashSet<WorkersBenefits>();
        }
    
        public int ID { get; set; }
        public Nullable<int> EmployerID { get; set; }
        public string WorkerID { get; set; }
        public string WorkerName { get; set; }
        public Nullable<int> JobType { get; set; }
        public Nullable<int> Seniority { get; set; }
        public string Email { get; set; }
        public string WorkerUserName { get; set; }
        public string WorkerPassword { get; set; }
    
        public virtual Employers Employers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkersBenefits> WorkersBenefits { get; set; }
    }
}
